
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Button Browse_button;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView JobName_textview;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TextView NumCameras_textview;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	
	private global::Gtk.TextView JobDir_textview;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Button LoadCam_button;
	
	private global::Gtk.Button CreateScene_button;
	
	private global::Gtk.Button CreateTake_button;
	
	private global::Gtk.Label Job_label;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView DataTransfer_treeview;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow4;
	
	private global::Gtk.TreeView CameraFiles_treeview;
	
	private global::Gtk.ScrolledWindow scrolledwindow1;
	
	private global::Gtk.DrawingArea Connectors_drawingarea;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Events = ((global::Gdk.EventMask)(772));
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Events = ((global::Gdk.EventMask)(772));
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
		this.table1.WidthRequest = 600;
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.Browse_button = new global::Gtk.Button ();
		this.Browse_button.CanFocus = true;
		this.Browse_button.Name = "Browse_button";
		this.Browse_button.UseUnderline = true;
		this.Browse_button.Label = global::Mono.Unix.Catalog.GetString ("...");
		this.table1.Add (this.Browse_button);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.Browse_button]));
		w1.TopAttach = ((uint)(3));
		w1.BottomAttach = ((uint)(4));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.JobName_textview = new global::Gtk.TextView ();
		this.JobName_textview.WidthRequest = 500;
		this.JobName_textview.CanFocus = true;
		this.JobName_textview.Name = "JobName_textview";
		this.GtkScrolledWindow1.Add (this.JobName_textview);
		this.table1.Add (this.GtkScrolledWindow1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow1]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow2.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.NumCameras_textview = new global::Gtk.TextView ();
		this.NumCameras_textview.CanFocus = true;
		this.NumCameras_textview.Name = "NumCameras_textview";
		this.GtkScrolledWindow2.Add (this.NumCameras_textview);
		this.table1.Add (this.GtkScrolledWindow2);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow2]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow3.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.JobDir_textview = new global::Gtk.TextView ();
		this.JobDir_textview.CanFocus = true;
		this.JobDir_textview.Name = "JobDir_textview";
		this.GtkScrolledWindow3.Add (this.JobDir_textview);
		this.table1.Add (this.GtkScrolledWindow3);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow3]));
		w7.TopAttach = ((uint)(3));
		w7.BottomAttach = ((uint)(4));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.LoadCam_button = new global::Gtk.Button ();
		this.LoadCam_button.Sensitive = false;
		this.LoadCam_button.CanFocus = true;
		this.LoadCam_button.Name = "LoadCam_button";
		this.LoadCam_button.UseUnderline = true;
		this.LoadCam_button.Label = global::Mono.Unix.Catalog.GetString ("Load Camera");
		this.hbox3.Add (this.LoadCam_button);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LoadCam_button]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.CreateScene_button = new global::Gtk.Button ();
		this.CreateScene_button.Sensitive = false;
		this.CreateScene_button.CanFocus = true;
		this.CreateScene_button.Name = "CreateScene_button";
		this.CreateScene_button.UseUnderline = true;
		this.CreateScene_button.Label = global::Mono.Unix.Catalog.GetString ("Create Scene Dir");
		this.hbox3.Add (this.CreateScene_button);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.CreateScene_button]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.CreateTake_button = new global::Gtk.Button ();
		this.CreateTake_button.Sensitive = false;
		this.CreateTake_button.CanFocus = true;
		this.CreateTake_button.Name = "CreateTake_button";
		this.CreateTake_button.UseUnderline = true;
		this.CreateTake_button.Label = global::Mono.Unix.Catalog.GetString ("Create Take Dir");
		this.hbox3.Add (this.CreateTake_button);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.CreateTake_button]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.table1.Add (this.hbox3);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox3]));
		w11.TopAttach = ((uint)(4));
		w11.BottomAttach = ((uint)(5));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.Job_label = new global::Gtk.Label ();
		this.Job_label.Name = "Job_label";
		this.Job_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Job Dir");
		this.table1.Add (this.Job_label);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.Job_label]));
		w12.TopAttach = ((uint)(3));
		w12.BottomAttach = ((uint)(4));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Job Template");
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Job Name");
		this.table1.Add (this.label5);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Num of Cameras");
		this.table1.Add (this.label6);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed1.Add (this.table1);
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 350;
		this.GtkScrolledWindow.HeightRequest = 400;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.DataTransfer_treeview = new global::Gtk.TreeView ();
		this.DataTransfer_treeview.WidthRequest = 400;
		this.DataTransfer_treeview.HeightRequest = 400;
		this.DataTransfer_treeview.CanFocus = true;
		this.DataTransfer_treeview.Name = "DataTransfer_treeview";
		this.GtkScrolledWindow.Add (this.DataTransfer_treeview);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w18.X = 50;
		w18.Y = 300;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow4.WidthRequest = 150;
		this.GtkScrolledWindow4.HeightRequest = 400;
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.CameraFiles_treeview = new global::Gtk.TreeView ();
		this.CameraFiles_treeview.CanFocus = true;
		this.CameraFiles_treeview.Name = "CameraFiles_treeview";
		this.GtkScrolledWindow4.Add (this.CameraFiles_treeview);
		this.fixed1.Add (this.GtkScrolledWindow4);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow4]));
		w20.X = 500;
		w20.Y = 300;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.WidthRequest = 100;
		this.scrolledwindow1.HeightRequest = 400;
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Events = ((global::Gdk.EventMask)(772));
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w21 = new global::Gtk.Viewport ();
		w21.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.Connectors_drawingarea = new global::Gtk.DrawingArea ();
		this.Connectors_drawingarea.Events = ((global::Gdk.EventMask)(772));
		this.Connectors_drawingarea.Name = "Connectors_drawingarea";
		w21.Add (this.Connectors_drawingarea);
		this.scrolledwindow1.Add (w21);
		this.fixed1.Add (this.scrolledwindow1);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.scrolledwindow1]));
		w24.X = 400;
		w24.Y = 300;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 700;
		this.DefaultHeight = 790;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnButtonPress);
		this.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnMotionNotify);
		this.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnButtonRelease);
		this.LoadCam_button.Clicked += new global::System.EventHandler (this.OnLoadCamera);
		this.CreateScene_button.Clicked += new global::System.EventHandler (this.OnCreateSceneDir);
		this.CreateTake_button.Clicked += new global::System.EventHandler (this.OnCreateTakeDir);
		this.Browse_button.Clicked += new global::System.EventHandler (this.OnBrowse);
		this.DataTransfer_treeview.RowCollapsed += new global::Gtk.RowCollapsedHandler (this.OnDataTransferTreviewRowCollapsed);
		this.Connectors_drawingarea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnExpose);
	}
}
