
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VPaned vpaned_full_window;
	
	private global::Gtk.HPaned hpaned_Job_setup;
	
	private global::Gtk.Label Job_label;
	
	private global::Gtk.HPaned hpaned_dir_and_browse;
	
	private global::Gtk.TextView JobDir_textview;
	
	private global::Gtk.Button Browse_button;
	
	private global::Gtk.VPaned vpanel_Load_and_Treeview;
	
	private global::Gtk.HPaned hpaned_load_and_create;
	
	private global::Gtk.Button LoadCam_button;
	
	private global::Gtk.HPaned hpaned_create_scene_and_take;
	
	private global::Gtk.Button CreateScene_button;
	
	private global::Gtk.Button CreateTake_button;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView DataTransfer_treeview;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vpaned_full_window = new global::Gtk.VPaned ();
		this.vpaned_full_window.CanFocus = true;
		this.vpaned_full_window.Name = "vpaned_full_window";
		this.vpaned_full_window.Position = 35;
		// Container child vpaned_full_window.Gtk.Paned+PanedChild
		this.hpaned_Job_setup = new global::Gtk.HPaned ();
		this.hpaned_Job_setup.CanFocus = true;
		this.hpaned_Job_setup.Name = "hpaned_Job_setup";
		this.hpaned_Job_setup.Position = 64;
		// Container child hpaned_Job_setup.Gtk.Paned+PanedChild
		this.Job_label = new global::Gtk.Label ();
		this.Job_label.Name = "Job_label";
		this.Job_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Job");
		this.hpaned_Job_setup.Add (this.Job_label);
		global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.hpaned_Job_setup [this.Job_label]));
		w1.Resize = false;
		// Container child hpaned_Job_setup.Gtk.Paned+PanedChild
		this.hpaned_dir_and_browse = new global::Gtk.HPaned ();
		this.hpaned_dir_and_browse.CanFocus = true;
		this.hpaned_dir_and_browse.Name = "hpaned_dir_and_browse";
		this.hpaned_dir_and_browse.Position = 437;
		// Container child hpaned_dir_and_browse.Gtk.Paned+PanedChild
		this.JobDir_textview = new global::Gtk.TextView ();
		this.JobDir_textview.Buffer.Text = "Job Directory ...";
		this.JobDir_textview.CanFocus = true;
		this.JobDir_textview.Name = "JobDir_textview";
		this.hpaned_dir_and_browse.Add (this.JobDir_textview);
		global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned_dir_and_browse [this.JobDir_textview]));
		w2.Resize = false;
		// Container child hpaned_dir_and_browse.Gtk.Paned+PanedChild
		this.Browse_button = new global::Gtk.Button ();
		this.Browse_button.CanFocus = true;
		this.Browse_button.Name = "Browse_button";
		this.Browse_button.UseUnderline = true;
		this.Browse_button.Label = global::Mono.Unix.Catalog.GetString ("...");
		this.hpaned_dir_and_browse.Add (this.Browse_button);
		this.hpaned_Job_setup.Add (this.hpaned_dir_and_browse);
		this.vpaned_full_window.Add (this.hpaned_Job_setup);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.vpaned_full_window [this.hpaned_Job_setup]));
		w5.Resize = false;
		// Container child vpaned_full_window.Gtk.Paned+PanedChild
		this.vpanel_Load_and_Treeview = new global::Gtk.VPaned ();
		this.vpanel_Load_and_Treeview.CanFocus = true;
		this.vpanel_Load_and_Treeview.Name = "vpanel_Load_and_Treeview";
		this.vpanel_Load_and_Treeview.Position = 57;
		// Container child vpanel_Load_and_Treeview.Gtk.Paned+PanedChild
		this.hpaned_load_and_create = new global::Gtk.HPaned ();
		this.hpaned_load_and_create.CanFocus = true;
		this.hpaned_load_and_create.Name = "hpaned_load_and_create";
		this.hpaned_load_and_create.Position = 190;
		// Container child hpaned_load_and_create.Gtk.Paned+PanedChild
		this.LoadCam_button = new global::Gtk.Button ();
		this.LoadCam_button.Sensitive = false;
		this.LoadCam_button.CanFocus = true;
		this.LoadCam_button.Name = "LoadCam_button";
		this.LoadCam_button.UseUnderline = true;
		this.LoadCam_button.Label = global::Mono.Unix.Catalog.GetString ("Load Camera");
		this.hpaned_load_and_create.Add (this.LoadCam_button);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.hpaned_load_and_create [this.LoadCam_button]));
		w6.Resize = false;
		// Container child hpaned_load_and_create.Gtk.Paned+PanedChild
		this.hpaned_create_scene_and_take = new global::Gtk.HPaned ();
		this.hpaned_create_scene_and_take.CanFocus = true;
		this.hpaned_create_scene_and_take.Name = "hpaned_create_scene_and_take";
		this.hpaned_create_scene_and_take.Position = 194;
		// Container child hpaned_create_scene_and_take.Gtk.Paned+PanedChild
		this.CreateScene_button = new global::Gtk.Button ();
		this.CreateScene_button.Sensitive = false;
		this.CreateScene_button.CanFocus = true;
		this.CreateScene_button.Name = "CreateScene_button";
		this.CreateScene_button.UseUnderline = true;
		this.CreateScene_button.Label = global::Mono.Unix.Catalog.GetString ("Create Scene Dir");
		this.hpaned_create_scene_and_take.Add (this.CreateScene_button);
		global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.hpaned_create_scene_and_take [this.CreateScene_button]));
		w7.Resize = false;
		// Container child hpaned_create_scene_and_take.Gtk.Paned+PanedChild
		this.CreateTake_button = new global::Gtk.Button ();
		this.CreateTake_button.Sensitive = false;
		this.CreateTake_button.CanFocus = true;
		this.CreateTake_button.Name = "CreateTake_button";
		this.CreateTake_button.UseUnderline = true;
		this.CreateTake_button.Label = global::Mono.Unix.Catalog.GetString ("Create Take Dir");
		this.hpaned_create_scene_and_take.Add (this.CreateTake_button);
		this.hpaned_load_and_create.Add (this.hpaned_create_scene_and_take);
		this.vpanel_Load_and_Treeview.Add (this.hpaned_load_and_create);
		global::Gtk.Paned.PanedChild w10 = ((global::Gtk.Paned.PanedChild)(this.vpanel_Load_and_Treeview [this.hpaned_load_and_create]));
		w10.Resize = false;
		// Container child vpanel_Load_and_Treeview.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.DataTransfer_treeview = new global::Gtk.TreeView ();
		this.DataTransfer_treeview.CanFocus = true;
		this.DataTransfer_treeview.Name = "DataTransfer_treeview";
		this.GtkScrolledWindow.Add (this.DataTransfer_treeview);
		this.vpanel_Load_and_Treeview.Add (this.GtkScrolledWindow);
		this.vpaned_full_window.Add (this.vpanel_Load_and_Treeview);
		this.Add (this.vpaned_full_window);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 588;
		this.DefaultHeight = 530;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Browse_button.Clicked += new global::System.EventHandler (this.OnBrowse);
		this.LoadCam_button.Clicked += new global::System.EventHandler (this.OnLoadCamera);
		this.CreateScene_button.Clicked += new global::System.EventHandler (this.OnCreateSceneDir);
		this.CreateTake_button.Clicked += new global::System.EventHandler (this.OnCreateTakeDir);
		this.DataTransfer_treeview.RowCollapsed += new global::Gtk.RowCollapsedHandler (this.OnDataTransferTreeviewRowCollapsed);
	}
}
